### ISSUE TITLE
Append mode with string columns

### ISSUE THREAD

**Issue by ThalesMR** [innobi/pantab#108]
**Describe the bug**
I read a DF from SQLServer in chunk, but when I try to append it to my hyperfile it was raising typerror for all text columns:

TypeError: Mismatched column definitions: (Name="ID (End User)", Type=TEXT, Nullability=Nullability.NULLABLE), (Name="Name (End User)", Type=TEXT, Nullability=Nullability.NULLABLE),...

PS: I casted all types for all columns before try to append the DF.

**Comment by WillAyd** [comment]
Can you provide a small code sample to reproduce the error?

**Comment by ThalesMR** [comment]
=========================================================================
query_select = f"SELECT * FROM {schema}.{table}"
    chunksize = 20000
    for i, chunk in  enumerate(pd.read_sql_query(query_select, parse_dates=True,con=cnxn, chunksize=chunksize)):
        #fix data type issues
        for k in columns_dict:
            fix_type(chunk,k,columns_dict[k])
        if i == 0:
            file_name = create_hyper(chunk,config["target"])
        else:
            create_hyper(chunk,config["target"],'a')
========================================================================

I notice that it may have (for some reason) a diferent column order for each chink, so I'm testing it with reindex columns

**Comment by WillAyd** [comment]
Unfortunately I can't run that code snippet. This guide might be helpful to provide information:


https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

It would also be helpful if you provide the full traceback

**Comment by ThalesMR** [comment]
Problem solved, I only had to reindex columns and it works.
