### ISSUE TITLE
Support for additional Pandas dtypes

### ISSUE THREAD

**Issue by caleboverman** [innobi/pantab#130]
**Is your feature request related to a problem? Please describe.**
Pandas has continued to introduce new dtypes using their `ExtensionArray`. While `Int64` is supported by Pantab, newer types `Float32` and `Float64` (introduced in Pandas 1.2.0) are not supported. Pantab also lacks support for writing `category` types.

**Describe the solution you'd like**
Support writing `Float32` and `Float64` types just as `float32` and `float64`. Additionally, I think `category` should be supported by writing values as a text field in Hyper.

**Comment by WillAyd** [comment]
Thanks for the suggestion. You can add mappings for the `Float32` and `Float64` types here if it's a contribution you'd like to try out:

https://github.com/innobi/pantab/blob/df96eee4a90a05fae43cbac6a638b90897bf7ef3/pantab/_types.py#L21

Be sure to check the contributing guide as well for how to pair with tests. Note that the Hyper API only offers a DOUBLE type, so float32 / float 64 end up being the same size in Hyper

I'm not sure about your suggestion for the `category` type though. It's a bit ambiguous that that is what the user would want to have happen versus them explicitly casting to a string, or maybe writing out the encoded values instead. Implicitly casting for the user can have some serious performance implications as well

**Comment by caleboverman** [comment]
Thanks I've got most of the float work built out. Curious your thoughts on round tripping these types. I don't typically read from a hyper extract but I know the library supports it. Should we default to reading back to `Float32`/`Float64` if the Pandas version >= 1.2.0 or stick with the more common `float32`/`float64`?

Figured the `category` proposal might warrant more discussion as I certainly understand the concerns. Personally, I prefer to see a sane default instead of failing. What about accepting a dict mapping categorical column names to a Tableau type? Another option might be leveraging `convert_dtypes` to infer a non-categorical type that might be best.

**Comment by WillAyd** [comment]
At least for non-nullable DOUBLE I would prefer to stick with the normal `float64` when reading back from Hyper, as it won't have the overhead of a mask that `Float64` does. 

I don't have a strong opinion when the type is detected as NULLABLE on the Hyper side, but it might be nice to return `Float64` in that case since we do `IntXX` when nullability is detected, so we'd be more consistent on the numeric side of things

**Comment by WillAyd** [comment]
> Figured the `category` proposal might warrant more discussion as I certainly understand the concerns. Personally, I prefer to see a sane default instead of failing. What about accepting a dict mapping categorical column names to a Tableau type? Another option might be leveraging `convert_dtypes` to infer a non-categorical type that might be best.

Interesting idea. Maybe a simple keyword that allows you to use the key or the value for a categorical would suffice. Bonus points if that means we don't need the added overhead of creating an extra string column when value is chosen. I'd probably start with just one keyword to keep things simple rather than a dict mapping; it feels like it would be a rare use case for users to mix and match using keys versus values in different columns of the same data frame

**Comment by caleboverman** [comment]
By key I assume you mean `df[column].cat.codes`. Could definitely do that but there would be no mapping to use on the Tableau side. I also don't know how pandas generates the mapping - my worry would be that ordering within the dataframe could matter. In this case, if you've got an existing extract that you're appending new data to, how do you ensure the mappings are the same?

**Comment by WillAyd** [comment]
Fair points. Would definitely consider anything you want to post a PR for. Probably easier to do the numeric stuff first or at least separate

From: Caleb Overman ***@***.***>
Reply-To: innobi/pantab ***@***.***>
Date: Monday, April 26, 2021 at 10:54 AM
To: innobi/pantab ***@***.***>
Cc: will_ayd ***@***.***>, Comment ***@***.***>
Subject: Re: [innobi/pantab] Support for additional Pandas dtypes (#130)


By key I assume you mean df[column].cat.codes. Could definitely do that but there would be no mapping to use on the Tableau side. I also don't know how pandas generates the mapping - my worry would be that ordering within the dataframe could matter. In this case, if you've got an existing extract that you're appending new data to, how do you ensure the mappings are the same?
