### ISSUE TITLE
Support for PyArrow tables

### ISSUE THREAD

**Issue by caleboverman** [innobi/pantab#133]
Curious if you've looked at generating an extract from a PyArrow table? I'm not sure how much performance benefit there might be over #132 (which I'm really excited for) as a dataframe would obviously need to be converted to a pyarrow table. But my primary use case for pantab is converting parquet files into tableau extracts, so it ends up going parquet -> pyarrow -> pandas -> tableau. Completely understand if it's outside your scope here.

**Comment by WillAyd** [comment]
I haven't looked at that yet but something to consider. Hyper also allows you to read parquet files directly which you might want to try out

https://help.tableau.com/current/api/hyper_api/en-us/reference/sql/sql-copy.html#SQL-COPY-APACHE_PARQUET_FORMAT

@vogelsgesang

**Comment by vogelsgesang** [comment]
If all you need to do is to get a Parquet file into Hyper, directly using HyperAPI to do so is probably the fastest way.
However, you will have to sacrifice some convenience to do so: E.g., you will no longer get "schema inference" for free. Instead you would need to explicitly specify the column names and column types.

The easiest way to get going with Hyper's ParquetScan is probably to start with the [CSV import example](https://github.com/tableau/hyper-api-samples/blob/main/Tableau-Supported/Python/create_hyper_file_from_csv.py) and change the `(format csv, NULL 'NULL', delimiter ',', header)` to `format parquet`.

**Comment by WillAyd** [comment]
I have been using pyarrow more and am definitely prioritizing this a little higher. If I get some time I'd love to tackle, though also happy to partner on something if there's interest from you @caleboverman

**Comment by WillAyd** [comment]
Structurally it's probably best served as its own repo (`hyperarrow-core` ???) and then pantab really just really wraps that in Python using a `pa.Table.from_pandas(df)` call

**Comment by caleboverman** [comment]
Definitely interested in working together.

I've debated how to structure this. Seems as though pantab will be such a small wrapper that it might not justify separating them. Not sure I feel strongly either way and am open to what you think is best.

**Comment by WillAyd** [comment]
It’s probably best served as a separate project. Arrow is supposed to be language agnostic with bindings available in various languages. Mirroring that design we would have a separate repo for the core integration between arrow / hyper and pantab would be one binding that uses that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by caleboverman** [comment]
Great point. I was thinking pretty specifically about the pandas/python use case rather than more generally.

**Comment by WillAyd** [comment]
A separate repo is a little more ambitious, so I’d be open to starting here and tackling in small chunks too

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by caleboverman** [comment]
Agreed that leveraging everything we can from the existing pantab repo to experiment with is helpful.

Any thoughts on how where to start?

**Comment by WillAyd** [comment]
Yea I would think the starting point is to get a new extension module in place that uses the arrow library natively. Probably best to pick either the reader or writer and switch them over to using that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WillAyd** [comment]
Hacked together a Dockerfile to build arrow and tableau together, using the examples from the arrow repo. Not pretty but a starting point.

Next time is to start filling in some code to actually leverage both of the built libraries. Happy to have any kind of PR you'd like to contribute

https://github.com/innobi/hyperarrow

**Comment by WillAyd** [comment]
@caleboverman this is underway at the new hyper arrow project. If you are on macOS there is already a wheel available that you can test out:

https://github.com/innobi/hyperarrow/actions/runs/1552161232

I will be adding other platforms soon. If you want to let me know which you are using I'll try to prioritize it

Closing this issue as I don't have any near term plans to do this in pantab. I *think* these are better served as separate libraries, though that may change in the future as we learn more. In such case will either re-open or start a new issue.

Thanks!

**Comment by caleboverman** [comment]
@WillAyd apologize for the silence. Hoping to have an opportunity to dive in over the holiday.

I'll be on mac and have both intel and m1 to utilize.
