### ISSUE TITLE
Import Error on Colab: ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by Btibert3** [innobi/pantab#142]
**Describe the bug**
On Google Colab, `import pantab` throws the following error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-1-acefadb51d2f>](https://localhost:8080/#) in <module>()
      1 # imports
      2 import pandas as pd
----> 3 import pantab

[/usr/local/lib/python3.7/dist-packages/pantab/__init__.py](https://localhost:8080/#) in <module>()
      1 __version__ = "2.0.0"
      2 
----> 3 import libpantab  # type: ignore
      4 from ._reader import frame_from_hyper, frame_from_hyper_query, frames_from_hyper
      5 from ._tester import test

ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------


NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**To Reproduce**

```python
! pip install pantab
import pandas as pd
import pantab
```

**Expected behavior**
No error and import is successful. This has worked in the past, and it's not clear what version of numpy is now supported.

**Screenshots**

**Desktop (please complete the following information):**
 - Google Colab

**Additional context**

**Comment by WillAyd** [comment]
Thanks for the report. Which version of numpy is in use? The trace back leads me to believe there is a binary incompatibility between the numpy on CoLab and the one that the pantab wheel is compiled against

**Comment by WillAyd** [comment]
Also which version of Python are you using?

**Comment by Btibert3** [comment]
Nothing jumps out to me, and it doesn't appear that the colab team is
pinning the version of numpy to the build.

https://github.com/googlecolab/colabtools/blob/main/setup.py

**Comment by WillAyd** [comment]
We can rebuild the wheels if we pin numpy to 1.19 in the wheel building CI:

https://github.com/innobi/pantab/blob/40fad3f91a480807dd7690738549b0830cef5ac1/.github/workflows/pythonpublish.yml#L29

There's a few places in there to pin the lower end of numpy. 

Any interest in submitting a PR to do that? If so we might be able to have you try out the rebuilt wheel in colab

**Comment by WillAyd** [comment]
Hmm nevermind I don't think changing those files will do anything. Already tried and can't even build the wheel:

https://github.com/innobi/pantab/actions/runs/1820343375

Not sure what is up yet; will have to dig more

**Comment by WillAyd** [comment]
@Btibert3 can you try the wheel built here?

https://github.com/innobi/pantab/actions/runs/1821011078

FYI it doesn't look like numpy has wheels built for 3.10 for that far back, so this gets a bit into the question of how many python versions we can concurrently support (most scientific libraries only do 3)...

But for now let's see if this wheel gets you moving along

**Comment by Btibert3** [comment]
Things look pretty good.  Here is the Colab notebook that I used to test.  Feel free to poke holes but it did not throw an error.

https://colab.research.google.com/drive/1zkHKUTj_7qDmi5QuJ67CTscEo6NakLeL?usp=sharing

**Comment by WillAyd** [comment]
Are you able to upgrade to python 3.8? I still need to fix these in other wheels but have since dropped 3.7 in lieu of 3.10

**Comment by Btibert3** [comment]
I don't believe that Colab allows you to specify anything about the
runtime.  The most you can do is attempt to override/modify the pre-loaded
libraries.

**Comment by Btibert3** [comment]
Got it.  Unfortunately users have absolutely no control over much of the configuration in Colab short of install/update/downgrade packages per session.  I would imagine that Colab is not the primary environment for the use of pantab, but it is extremely popular in teaching contexts.

**Comment by WillAyd** [comment]
Yep understood. Glad we’ve got it for now - let me know if anything else pops up. Really appreciate it!

**Comment by whylovegithub** [comment]
I am having the same problem in python 3.9 and pantab 3.0.0 
any suggestion fixing this?

**Comment by whylovegithub** [comment]
![image](https://github.com/innobi/pantab/assets/32151841/0059844b-ae2e-4603-a2dc-be822eab951e)

**Comment by whylovegithub** [comment]
![image](https://github.com/innobi/pantab/assets/32151841/078cca43-d8b7-45ad-a55c-3354b39325ff)
