### ISSUE TITLE
Pantab errors

### ISSUE THREAD

**Issue by amitsureka** [innobi/pantab#154]
**Describe the bug**

Pantab failing with these errors:

Compiledffi object has no attribute release

System error: built in function 
read_hyper_query returned Null without setting an error

**To Reproduce**

Python 3.6 Windows 10, Pantab failing with above errors on using Pycharm.

Using Pantab 1.1.1

**Expected behavior**
Pantab frame from Hyper and frame to hyper failing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by WillAyd** [comment]
Can you try using a newer version of Python? We don't support 3.6 anymore at this point so want to rule that out

**Comment by WillAyd** [comment]
FYI we don't even support 3.7 any longer as we try to support 3 minor Python versions at a time. That currently puts us in 3.8, 3.9 and 3.10 being supported

**Comment by amitsureka** [comment]
Thanks a ton william...will try a newer python version.

Meanwhile when i downgraded tableauhyperapi to 0.0.14401 to use with pantab 1.1.1 ...it started to work fine...

Do you think using tableauhyperapi version 0.0.145 something was breaking pantab(default which pantab 1.1.1 installs)

**Comment by WillAyd** [comment]
Yea this sounds like #145

**Comment by WillAyd** [comment]
Given aforementioned issue I am going to close this one as a duplicate. If there's something unique here let me know and we can reopen with more info

Thanks for using the tool and providing feedback!
