### ISSUE TITLE
Pantab is eating RAM

### ISSUE THREAD

**Issue by maffka123** [innobi/pantab#155]
**Describe the bug**
I am trying to use pantab for a big table load (~150 Mln rows) to Tableau. So the process looks like that: DB -> table_part(500k)_to_hyper -> Tableau. Basically 300 times I do the same in a loop. I have noticed that something in the program blocks RAM and never gives it back. Memory profiling shows that it happens in the part where pantab is located. Unfortunately, I cannot see details. But when I switched back to tableau hyper API my service is using again 1 Gb of RAM instead of eating it up to 25 Gb and breaking the service.

**To Reproduce**

```python
    def write_hyper(self, df, path_to_database):
        for col in df.columns:
            if (
                df[col].dtype.name == "object"
                and df[col].notna().any()
                and isinstance(df[df[col].notna()][col].values[0], datetime.date)
            ):
                # df[col] = pd.to_datetime(df[col])
                df[col] = df[col].astype("datetime64")
        with HyperProcess(
            telemetry=Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU,
            parameters={"log_config": ""},
        ) as hyper:
            pantab.frame_to_hyper(
                df=df,
                database=path_to_database,
                table="Extract",
                hyper_process=hyper,
            )
```

**Expected behavior**
It does not use RAM infinitely

**Screenshots**
With pantab
![image](https://user-images.githubusercontent.com/19744910/162017626-5a48cc2e-2540-417b-ad59-ec3513213b1d.png)

Without pantab
![image](https://user-images.githubusercontent.com/19744910/162017919-5b0ee291-904a-4755-b91a-3dc20febe350.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - OS: Debian (docker image based on  python:3.9.2-slim-buster)

**Additional context**
Maybe it is not pantab itself, but pandas, but still it makes the library unusable for my usecase.

**Comment by WillAyd** [comment]
Does it make a difference at all if you don’t create a Hyper process and let pantab manage that for you?

Also can you provide a minimally reproducible example? 

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by maffka123** [comment]
Hi,
I just thought that I will report it. I decided not to use the tool..

Here is an example for you

```python
import pantab
import pandas as pd
import numpy as np
import os
import tracemalloc


def write_hyper(df, path_to_database):
    pantab.frame_to_hyper(
        df=df,
        database=path_to_database,
        table="Extract",
    )


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    c = list('qwertzuiopasdfghjklyxcvbnm')
    df = pd.DataFrame(np.random.randint(100, size=(500000, len(c))), columns=c)
    print(df.size)
    for i in range(300):
        tracemalloc.start()
        write_hyper(df, 'test.hyper')
        os.remove("test.hyper")
        snapshot = tracemalloc.take_snapshot()
        stats = snapshot.statistics('lineno')
        size = sum(stat.size for stat in stats)
        print("RAM: %.1f KiB" % (size / 1024))
```

If you make df heavier, you can enjoy how memory goes up infinitely
