### ISSUE TITLE
frames_from_hyper not pulling when there's no data in the table.  

### ISSUE THREAD

**Issue by VDFaller** [innobi/pantab#163]
**Describe the bug**
I'm simply trying to pull all the frames from a hyper file (which I unfortunately can't give you).  But I think the problem is that one of the tables doesn't have any rows. Which then errors out [here](https://github.com/innobi/pantab/blob/f6a9fbb3f73cd51ada79e5d6d6aa114aea77dc98/pantab/_reader.py#L50) with 

``` py
ValueError: Length mismatch: Expected axis has 0 elements, new values have 60 elements
```

df in the line above is an empty dataframe.  

This is a problem because it's screwing up my other reads. 

**Expected behavior**
It gives me a blank dataframe with the proper columns but no data.  

Could skip it too, but that seems worse.  

**Desktop (please complete the following information):**
 - OS: windows10

**Comment by VDFaller** [comment]
I can fix it by adding 

```py
if df.empty:
    df = pd.DataFrame(columns=dtypes.keys())
```
right before it.

**Comment by WillAyd** [comment]
Thanks for the note. If you’d like to create a pull request with a test it would be very welcome

**Comment by VDFaller** [comment]
Already making the MR.  I don't know how to use tableau so I don't know how to make a hyper , but I'll see if someone can help me over here.

**Comment by WillAyd** [comment]
I think you can still use pantab to write an empty dataframe? Or is that not working either?

**Comment by VDFaller** [comment]
Good point.  I'll try that.

**Comment by WillAyd** [comment]
That is unfortunate. Well if you are feeling ambitious here's I guide I wrote in pandas for how to debug their C extensions. The same rules should apply here in pantab

https://pandas.pydata.org/docs/development/debugging_extensions.html

**Comment by VDFaller** [comment]
Don't know if I have that kind of ambition at the moment.  But would it be helpful if I made a `test_roundtrip.py` test for it?  maybe with a `@pytest.mark.skip(reason="currently failing #163")` ?

**Comment by WillAyd** [comment]
I think the test there should work for reading/writing. I know the OP was just about reading but looks like neither work with an empty frame. Would make sense to fix togethee
