### ISSUE TITLE
Parquet Writer Implementation Not in pypi.org?

### ISSUE THREAD

**Issue by lhoggatt17** [innobi/pantab#168]
I'm getting an error that I believe would be fixed with the new parquet writer. However, it appears that the version on pypi has not been updated yet. Is this a function of there not being a version bump?

I'd really like to see if the new version fixed my issue. Is there any way we can get the new optional writer on pypi? 

Thanks!

**Comment by WillAyd** [comment]
Currently on vacation so just haven't gotten around to a new release. If you want to try you can use the source from GitHub

**Comment by WillAyd** [comment]
This has now been released
