### ISSUE TITLE
Memory Error when dataframe is empty

### ISSUE THREAD

**Issue by muhammadhamoud** [innobi/pantab#172]
**WhenI use pantab.frames_to_hyper() the following error arise if the dataframe is empty. **

```python
_insert_frame(
  File "lib\site-packages\pantab\_writer.py", line 157, in _insert_frame
    libpantab.write_to_hyper(df, null_mask, inserter._buffer, dtypes)
MemoryError
```
I have overcome the issue by passing the following commands
```python
if df.empty:
    df = pd.DataFrame(dict(zip(df.columns, [0 for _ in range(len(df.columns))])), index=[0])
```

**Comment by WillAyd** [comment]
Thanks for the issue. Want to try a PR to fix?

**Comment by muhammadhamoud** [comment]
Do you want me to pull request and fix it?

**Comment by WillAyd** [comment]
Sure that would be great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shaun-actionanalytics** [comment]
I ran into this issue today. Would be great to have a permanent fix.

**Comment by WillAyd** [comment]
Sure just need someone to contribute a patch. Would you be interested in doing that @shaun-actionanalytics ?
