### ISSUE TITLE
TypeError: Column "event_is_failure" has unsupported datatype BOOL with nullability Nullability.NULLABLE

### ISSUE THREAD

**Issue by keshavsainik** [innobi/pantab#177]
Hi, 

I was trying to extract a .hyper file and I got the above error, attached a screenshot as well. Could someone please help me on how I could resolve this issue. 

- pantab - 1.1.1
- tableauhyperapi - 0.0.14401
- python - 3.6

![image](https://user-images.githubusercontent.com/14050393/230318990-9ab2650a-e8df-43b5-8768-613b144bdc7a.png)

**Comment by WillAyd** [comment]
That is a pretty old version of pantab (released 2.5 years ago) and Python (we only support 3.8 forward right now). I'm pretty sure if you upgrade your Python and libraries it will fix things for you - if not ping me and can reopen

**Comment by keshavsainik** [comment]
Hi @WillAyd,

Thanks for the response.

Our entire project works on Python 3.6 so I couldn't upgrade the Pantab to a higher version which doesn't have the issue. I ended using a roundabout way of using tableauhyperapi itself to query the table in the hyper file and extracted data via that.
