### ISSUE TITLE
Python 3.11 - pantab/src/pantab.c:6:10: fatal error: 'cffi.h' file not found

### ISSUE THREAD

**Issue by albertcwong** [innobi/pantab#178]
**Describe the bug**
Cannot pip install pantab

**To Reproduce**

```
pip install pantab
```

**Expected behavior**
Successfully installed pantab

**Screenshots**
      pantab/src/pantab.c:6:10: fatal error: 'cffi.h' file not found
      #include "cffi.h"
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pantab
Failed to build pantab
ERROR: Could not build wheels for pantab, which is required to install pyproject.toml-based projects

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1

**Additional context**
This is for Pantab 3.0.0
An older version of Pantab will install correctly (1.1.1)

**Comment by WillAyd** [comment]
Which version of Python are you using? And what is your platform for macOS? pypi has wheels for 3.8-3.10 on the intel processor.

If building from source you might need to install xcode, though I'd caution if on an m2 I'm not sure that the tableauhyperapi is supported

**Comment by albertcwong** [comment]
Python Version: 3.11.2
Intel chip
I have re-installed xcode a few times after hitting this issue over the past few months, and always end up reverting to pantab 1.1.1

**Comment by WillAyd** [comment]
There aren't any 3.11 wheels on PyPi currently. The last release of pantab (Sep 2022) predates the release of Python 3.11 (Oct 2022).

Would definitely take a PR to build 3.11 wheels. I think you would just need to add in this file:

https://github.com/innobi/pantab/blob/3b9731f2d34fdfbcb3665827e683c091ee2ccbf7/.github/workflows/pythonpackage.yml#L25

and in this file:

https://github.com/innobi/pantab/blob/3b9731f2d34fdfbcb3665827e683c091ee2ccbf7/.github/workflows/pythonpublish.yml#L13

**Comment by WillAyd** [comment]
You could also use any 3.8-3.11 version to get it to install today without problem. pantab 1.1.1 is pretty old so you are missing about 2.5 years worth of features from both pantab and the tableauhyperapi reverting back to that

**Comment by albertcwong** [comment]
that works, thanks for the quick response!

**Comment by Installka** [comment]
@WillAyd, are there any plans to add Python 3.11 support?

**Comment by WillAyd** [comment]
Yea can be added just need a PR to make it happen. I think just need to edit the files I linked above - would you be interested in submitting a pull request for that?

**Comment by Installka** [comment]
Never did that before, but I'll try, why not 😅

**Comment by dss010101** [comment]
experiencing this same issue.  is there a work around until the wheel is built?

**Comment by dss010101** [comment]
Confirmed im not able to pip install.  thanks much!
