### ISSUE TITLE
Column Ordering Not Preserved 

### ISSUE THREAD

**Issue by yapnel** [innobi/pantab#185]
I notice when writing from data frame to hyper, the ordering of columns in the data frame is not preserved in hyper. Is there a way of forcing that or is it a bug?

**Comment by WillAyd** [comment]
What version of Python, tableauhyperapi and pantab are you using?

**Comment by yapnel** [comment]
> What version of Python, tableauhyperapi and pantab are you using?

Python - 3.10.x
Pantab - 3
Tabhyperapi - 0.0.17360

**Comment by WillAyd** [comment]
Can you provide a code sample to reproduce the issue?

**Comment by WillAyd** [comment]
Closing for now - if you can provide code to reproduce happy to take a look. Thanks!
