### ISSUE TITLE
TypeError: Cannot use .astype to convert from timezone-naive dtype to timezone-aware dtype. Use obj.tz_localize instead or series.dt.tz_localize instead

### ISSUE THREAD

**Issue by abhinavDhulipala** [innobi/pantab#186]
**Describe the bug**
Pandas has finally deprecated using `#astypes` to convert between timezone aware and timezone naive data types. The postgres datatype is `timestamp without time zone`, yielded from 

```psql
SELECT
    column_name,
    data_type
FROM
    information_schema.columns
WHERE
    table_schema = 'redacted_schema' AND 
    table_name = 'redacted_table' AND
    column_name = 'redacted_column';
```
| column_name     | data_type                   |
|-----------------|-----------------------------|
| redacted_column | timestamp without time zone |

In python we get 
```python3
Timestamp(2023, 4, 17, 23, 3, 39, 0, UTC)
```
**To Reproduce**
Input the previously mentioned data type into a hyperfile and run `pantab#frame_from_hyper_query` with the latest version of pandas. 

**Expected behavior**
Expected to return a data frame after a query is run

**Screenshots**
Here's a stack trace
```python3
TypeError: Cannot use .astype to convert from timezone-naive dtype to timezone-aware dtype. Use obj.tz_localize instead or series.dt.tz_localize instead
```

**Desktop (please complete the following information):**
```bash
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**
Every pandas related package in the env I run
```bash
$ pip freeze | grep pandas
dagster-duckdb-pandas==0.19.14
dagster-pandas==0.19.14
pandas==2.0.3
pandas-flavor==0.6.0
```
The problem here is with line 57 of [_readers.py](https://github.com/innobi/pantab/blob/main/pantab/_reader.py#L57)

**Comment by WillAyd** [comment]
Thanks for investigating and finding the root cause. Want to try a PR to fix it?

**Comment by WillAyd** [comment]
Though I am unclear about the error message - it doesn't look like we are trying to `astype` to a tz-aware dtype. Might be a pandas bug

**Comment by abhinavDhulipala** [comment]
I'd love to give it a crack, thanks!
