### ISSUE TITLE
Regarding Limitation with Pantab1.1.0 with Date Datatype

### ISSUE THREAD

**Issue by mayankalteryx** [innobi/pantab#192]
**Is your feature request related to a problem? Please describe.**
We have recently started using Pantab from tableau hyper API for creation of hyper file. As we are handling a large datasets and continuous modifications of data, we are facing the limitations of Pantab1.10 which adds up by a feature (Added support for reading Hyper DATE columns as datetime64 objects in pandas (#94)). [Pantab documetation](https://pantab.readthedocs.io/en/stable/changelog.html?highlight=date#pantab-3-0-0-2022-09-14)

**Describe the solution you'd like**
Is there is any new release or newer version of Pantab is planned in upcoming months. Or is there is anyone who can help us to get through this. We basically want to modify the datatype in hyper file. Ex- DATE as Datatype it will add the time value 00:00:00 because of above highlighted text. 

**Describe alternatives you've considered**
 We want when we change the datatype in hyperfile it should not add any random time to the Date datatype. And it should take it as Date  datatype not datatime64.

**Comment by WillAyd** [comment]
Thanks for posting here. To kick off the discussion - I'm not really clear what you are looking for. Do you have a code sample of what you've tried, what the current result is and what you expect to see?

**Comment by mayankalteryx** [comment]
In Order to make you understand more simply when we use pantab to convert the DATE as Datatype the pantab adds a random time stamp to the date column. Due to ((Added support for reading Hyper DATE columns as datetime64 objects in pandas (https://github.com/innobi/pantab/pull/94).

So when we are making the changes and creating a data-source in tableau pantab is adding  random time stamp to the date column and vice versa for the time column.


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/AYX105066/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/AYX105066/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



DATEEEE | TIMEEE | DATETIMEEE
-- | -- | --
5/2/1989 | 2:02:03 AM | 1/31/2023 3:51
5/2/1989 0:00 | 12/30/1899 2:02:03 AM | 1/31/2023 3:51



</body>

</html>

So the second rows shows the addition of random date and time. Because at the time of conversion from hyperfile pantab reacts with Date datatype as Datetime64 and same for time.

Refer to the attached screenshots too.
![Date_tableau](https://github.com/innobi/pantab/assets/144801319/9c48109e-e1ec-43d3-bf5a-5d1ab1422526)
![time_tableau](https://github.com/innobi/pantab/assets/144801319/1175b618-e5d3-49ec-bc5c-ad6fe0fb9143)

**Comment by WillAyd** [comment]
Can you provide a self contained code sample to show this behavior?

**Comment by mayankalteryx** [comment]
![4630ac98-9fdf-445a-85e4-c5670911c94b](https://github.com/innobi/pantab/assets/144801319/74548f6e-94ee-4d31-9912-fdd84d0b54a4)
[pantab_code.txt](https://github.com/innobi/pantab/files/12604867/pantab_code.txt)


This is the code snippet and error! That we are facing!

**Comment by WillAyd** [comment]
Your problem is that you are storing Python datetime objects in an object array. You need an actual datetime array for it to be written - otherwise pantab thinks you are trying to write strings and errors as such

**Comment by WillAyd** [comment]
To be a little more clear can just do `df["Date"] = pd.to_datetime(df["Date"])` in your example to get an actual timestamp column

**Comment by mayankalteryx** [comment]
` if date_col:
            for column in date_col:
                df[column] = pd.to_datetime(df[column])
`

we are already doing the same thing you mentioned. But this doesn't gives us error but this add the timestamp part (00:00:00) to the date.

Which is not what we want because we are dealing with date Datatype. And this converts it to datetime.

**Comment by WillAyd** [comment]
With the numpy backend to pandas there is no native DATE type. Your best bet would be for something like this:

https://github.com/innobi/pantab/issues/138#issuecomment-964448852

Which needs a PR from the community to implement.
