### ISSUE TITLE
Segmentation Fault Error with frame_to_hyper Method

### ISSUE THREAD

**Issue by nishioka-shinji** [innobi/pantab#240]
Hello, I am trying to generate a Hyper file using the pantab frame_to_hyper method, but I am encountering a `Segmentation fault (core dumped)` error. As of January 16, 2024, this error was not occurring.

- Summary of the code where the error occurred:
```python

bq_client = bigquery.Client(credentials=credentials)
data_frame = bq_client.query(query, project=dataset_name).to_dataframe()

for column in data_frame.columns:
    if data_frame[column].dtype.name == 'dbdate' or data_frame[column].dtype.name == 'datetime64[us]':
        data_frame[column] = data_frame[column].astype('datetime64[ns]')
    elif data_frame[column].dtype.name == 'datetime64[us, UTC]':
        data_frame[column] = data_frame[column].dt.tz_convert(None)
        data_frame[column] = data_frame[column].astype('datetime64[ns]')

# https://github.com/innobi/pantab/issues/172
if data_frame.empty:
    data_frame = pd.DataFrame(dict(zip(data_frame.columns, [0 for _ in range(len(data_frame.columns))])), index=[0])

file_path = f"data/output/hyper_files/myhyperfile.hyper"
pantab.frame_to_hyper(data_frame, file_path, table="Extract")
```

- Environment:
  - Platform: Amazon Linux 2023 AMI 2023.3.20231218.0 x86_64 HVM kernel-6.1
  - Python Version: 3.9.16
  - pantab Version: 3.0.0
  - tableauhyperapi Version: 0.0.18441
- Solutions I have tried so far:
  - Upgrading Amazon Linux to version 2023.3.20240122.0
  - Downgrading tableauhyperapi to version 0.0.18369
  - Checking pantab's dependent libraries (there were no particular upgrades)
  - Running in Docker on Mac environment (Python 3.10.13) where the same error occurred
  - Debugging pantab's _writer.py (error occurred at the following line)
https://github.com/innobi/pantab/blob/7819629c5bf322dd358f7b050233587b1bf57d0f/pantab/_writer.py#L157

If you have any advice or comments regarding this issue, please let me know. Thank you very much.

**Comment by WillAyd** [comment]
Thanks for the report. Any chance you have tried this against the latest version of pantab here on github? You should be able to pip install directly from this URL.

**Comment by nishioka-shinji** [comment]
@WillAyd 
Thank you! I was able to confirm that it works with the latest version!
While I'm glad the latest version works, I would prefer to fix the version as much as possible. Is there any other way to achieve this?

**Comment by WillAyd** [comment]
If you or anyone else in the community would like to submit a PR to fix it I would happily review

**Comment by WillAyd** [comment]
Closing for now as I expect 4.0 to be released within a few months, where this is already solved
