### ISSUE TITLE
Remove Dependency on tableauhyperapi

### ISSUE THREAD

**Issue by WillAyd** [innobi/pantab#267]
We have a runtime dependency on the Tableauhyperapi. While this is not problematic in theory, in practice we have started to bundle our own copy of the Hyper API and executable with pantab 4.0, so downloading both pantab and the tableauhyperapi duplicates copies of those (only the former from pantab should be used). These are rather large files, so for users in containers or other space-constrained areas this is wasteful

The only thing we _really_ use from the tableauhyperapi Python library is the `TableName` object. A duck-typed version of this internal to pantab would help us break that dependency for runtime (keeping around for testing is OK)

**Comment by abhinavDhulipala** [comment]
I would love to see the tabluehyperapi gone as well. It keeps us from using apple silicon hardware. What is the plan for implementing [frame_from_hyper](https://github.com/innobi/pantab/blob/main/src/pantab/_reader.py#L53) without the hyperapi. It would seem like we would need to reimplement the `Connection` API, which seems like a bigger lift.

**Comment by WillAyd** [comment]
Hey @abhinavDhulipala - just to be clear the scope of this issue is to remove the dependency on the _Python_ package, but we still bundle a copy of the C++ library. 

I assume that won't help your use case, and I don't believe that would even be possible without violating contractual terms for using the Hyper API
