### ISSUE TITLE
RecordBatchReader to_hyper yields Process finished with exit code

### ISSUE THREAD

**Issue by WillAyd** [innobi/pantab#281]
Reported by Jeremy Harris on the Tableau slack:

> when I try to pass a RecordBatchReader returned by ADBC, I get Process finished with exit code -1073741819 (0xC0000005). When I evaluate that same reader to a Table, it finishes successfully. Not sure if this is an issue or something to do with ADBC flavor RecordBatchReaders

Errors:

```python
import adbc_driver_postgresql.dbapi
import pantab

conn_uri = f"postgresql://readonly:password@my-server-url:8060/workgroup"
with adbc_driver_postgresql.dbapi.connect(conn_uri) as conn:
  with conn.cursor() as cur:
    sql = f"select * from public.workbooks"
    cur.execute(sql)
    arrow_batch_reader = cur.fetch_record_batch()
    pantab.frame_to_hyper(df=arrow_batch_reader, database="example.hyper", table="table", table_mode="w")
```

Succeeds:

```python
import adbc_driver_postgresql.dbapi
import pantab

conn_uri = f"postgresql://readonly:password@my-server-url:8060/workgroup"
with adbc_driver_postgresql.dbapi.connect(conn_uri) as conn:
  with conn.cursor() as cur:
    sql = f"select * from public.workbooks"
    cur.execute(sql)
    arrow_batch_reader = cur.fetch_record_batch()
    arrow_table = arrow_batch_reader.read_all()
    pantab.frame_to_hyper(df=arrow_table, database="example.hyper", table="table", table_mode="w")
```

**Comment by jharris126** [comment]
It looks like this was a known issue in [arrow-adbc](https://github.com/apache/arrow-adbc)'s python driver in <0.10. Per resolution of [1523](https://github.com/apache/arrow-adbc/issues/1523), it looks like they removed a customer wrapper they had around the `RecordBatchReader` and [now return a "real" reader](https://github.com/apache/arrow-adbc/blob/0d20d48f0df1800bb75ce077ad6a7be9cf754543/python/adbc_driver_manager/adbc_driver_manager/dbapi.py#L1092-L1095).

Upgrading both `adbc_driver_postgresql` and `adbc_driver_manager` to >=0.10 resolves the issue and the below script completes as expected:
```python
import adbc_driver_postgresql.dbapi
import pantab

conn_uri = f"postgresql://readonly:password@my-server-url:8060/workgroup"
with adbc_driver_postgresql.dbapi.connect(conn_uri) as conn:
  with conn.cursor() as cur:
    sql = f"select * from public.workbooks"
    cur.execute(sql)
    arrow_batch_reader = cur.fetch_record_batch()
    pantab.frame_to_hyper(df=arrow_batch_reader, database="example.hyper", table="table", table_mode="w")
```


Additionally, the workaround for arrow-adbc versions <0.10 is to force using the raw protected `_reader` property:
```python
import adbc_driver_postgresql.dbapi
import pantab

conn_uri = f"postgresql://readonly:password@my-server-url:8060/workgroup"
with adbc_driver_postgresql.dbapi.connect(conn_uri) as conn:
  with conn.cursor() as cur:
    sql = f"select * from public.workbooks"
    cur.execute(sql)
    arrow_batch_reader = cur.fetch_record_batch()._reader
    pantab.frame_to_hyper(df=arrow_batch_reader, database="example.hyper", table="table", table_mode="w")
```

This Issue can be closed.
