### ISSUE TITLE
`Date32` dates are off when written to hyper file

### ISSUE THREAD

**Issue by rayanedlebi-jb** [innobi/pantab#282]
**Bug Description**
When a `Date32` column is included in a `pyarrow` table, the the dates seem to skew (at least for dates after 2024-01-31) upon hyper creation. See examples:
- `2024-02-01` **triggers issue** (writes 2024-03-03 instead)
- `2024-03-16` **triggers issue** (writes 2024-05-15 instead)
- `2024-03-01` **triggers issue** (writes 2024-04-30 instead)
- `2024-01-01` successfully writes 2024-01-01 (does not trigger issue)
- `2024-01-31` successfully writes 2024-01-31 (does not trigger issue)

**Versions Tested On**
- Windows 10 machine
  - Python 3.11.8
  - pantab 4.0
- Databricks enviornment
  - Python 3.9.5
  - pantab 4.0

**To Reproduce**
Use following script to reproduce (same dates referenced earlier):
```python
import datetime
import pyarrow as pa
import pantab as pt

def basic_arrow_table():
    schema = pa.schema(
        [
            ("date32_test_col", pa.date32())
        ]
    )

    tbl = pa.Table.from_arrays(
        [
            pa.array(
                [
                    datetime.date(2024,2,1), # TRIGGERS ISSUE: (writes 2024-03-03 instead)
                    datetime.date(2024, 3, 16), # TRIGGERS ISSUE: (writes 2024-05-15 instead)
                    datetime.date(2024, 3, 1), # TRIGGERS ISSUE: (writes 2024-04-30 instead)
                    datetime.date(2024, 1, 1), # DOES NOT TRIGGER ISSUE
                    datetime.date(2024, 1, 31) # DOES NOT TRIGGER ISSUE
                ]
            )
        ],
        schema=schema
    )

    return tbl

tbl = basic_arrow_table()

pt.frame_to_hyper(tbl, "pantab_hyper_defect_test.hyper", table="extract")
```

Resulting dates written:
<img width="633" alt="image" src="https://github.com/innobi/pantab/assets/97246612/75f785af-8fba-47d6-a1f6-399730dc6899">

**Comment by WillAyd** [comment]
Thanks for the bug report. Looks like a typo that caused this - will release a bugfix version soon

**Comment by rayanedlebi-jb** [comment]
> Thanks for the bug report. Looks like a typo that caused this - will release a bugfix version soon

Thank you @WillAyd !
