### ISSUE TITLE
Failure to import 4.x

### ISSUE THREAD

**Issue by fxstempfelals** [innobi/pantab#287]
**Describe the bug**
After installing the package with pip, either version 4.0.0 or 4.0.1, trying to import the package raises an error:

**To Reproduce**

```
(base) fxstempfel@jupyter-85f8b9d48-6zh6c:~/workspace.git$ python -c "import pantab"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/pantab/__init__.py", line 4, in <module>
    from pantab._reader import frame_from_hyper, frame_from_hyper_query, frames_from_hyper
  File "/opt/conda/lib/python3.9/site-packages/pantab/_reader.py", line 10, in <module>
    import pantab.libpantab as libpantab
ImportError: /opt/conda/lib/python3.9/site-packages/pantab/libpantab.cpython-39-x86_64-linux-gnu.so: undefined symbol: hyper_big_numeric_to_double
```

**Expected behavior**
The package is imported without error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 on Docker

**Additional context**

```
(base) fxstempfel@jupyter-85f8b9d48-6zh6c:~/workspace.git$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```
(base) fxstempfel@jupyter-85f8b9d48-6zh6c:~/workspace.git$ pip show pip pantab
Name: pip
Version: 24.0
Summary: The PyPA recommended tool for installing Python packages.
Home-page: 
Author: 
Author-email: The pip developers <distutils-sig@python.org>
License: MIT
Location: /opt/conda/lib/python3.9/site-packages
Requires: 
Required-by: 
---
Name: pantab
Version: 4.0.1
Summary: Converts pandas DataFrames into Tableau Hyper Extracts and back
Home-page: 
Author: 
Author-email: Will Ayd <will_ayd@innobi.io>
License: BSD 3-Clause License
        
        Copyright (c) 2018-2024 William Ayd and innobi, LLC
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distribution.
        
        * Neither the name of the copyright holder nor the names of its
          contributors may be used to endorse or promote products derived from
          this software without specific prior written permission.
        
        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: /opt/conda/lib/python3.9/site-packages
Requires: pyarrow, tableauhyperapi
Required-by: 
```

**Comment by jorwoods** [comment]
What exact container are you using? I tested with two and was not able to reproduce.

```bash
docker run -it python:3.9.10-bullseye /bin/bash
pip install --user pantab
python -c "import pantab"
```
and 
```bash
docker run -it python:3.11.8-bookworm /bin/bash
pip install --user pantab
python -c "import pantab"
```

Both run successfully without issue.

**Comment by jorwoods** [comment]
The following also ran successfully:

```bash
docker run -it continuumio/anaconda3:2024.02-1 /bin/bash
conda create -n py39 python=3.9
conda activate py39
pip install pantab
python -c "import pantab"
```

**Comment by fxstempfelals** [comment]
I think it is due to some kind of conflict with other libraries, my suspect being numpy/tableauserverapi.
Unfortunately, I don't have access to docker directly and cannot test this on a fresh container, but running this makes the error appear in my environment:
`pip install numpy==1.24.4 tableauhyperapi==0.0.14567 pantab==4.0.1`

But if afterwards, I run `pip install --force-reinstall pantab==4.0.1`, then I can import pantab successfully.
Sorry I can't produce some code to reproduce the error...

**Comment by jorwoods** [comment]
After the forced reinstall, are numpy and tableauhyperapi the same versions you listed above, or was that before the reinstall?

**Comment by fxstempfelals** [comment]
This is the last line of the force reinstall output:
`Successfully installed cffi-1.16.0 numpy-1.26.4 pantab-4.0.1 pyarrow-15.0.2 pycparser-2.21 tableauhyperapi-0.0.18825`

So numpy and tableauhyperapi are both updated in the process.

**Comment by WillAyd** [comment]
Oof...well this is a good impetus for https://github.com/innobi/pantab/issues/267

Right now with pantab we actually build against and distribute our own copy of the tableau hyper api. 

```sh
root@7f1cc8445551: python3.9 -m pip install tableauhyperapi==0.0.14567 pantab==4.0.1
root@7f1cc8445551: cd /usr/local/lib/python3.9/dist-packages
root@7f1cc8445551:/usr/local/lib/python3.9/dist-packages# find . -name "*hyperapi.so*"
./tableauhyperapi/bin/libtableauhyperapi.so
./pantab/libtableauhyperapi.so
```

If you look at the library we distribute, the symbol from the error message in the OP exists:

```sh
root@7f1cc8445551:/usr/local/lib/python3.9/dist-packages# nm pantab/libtableauhyperapi.so -gDC | grep hyper_big_numeric_to_double
0000000000d8b630 T hyper_big_numeric_to_double
```

but that symbol does not exist in the tableauhyperapi distributed shared library:

```sh
root@7f1cc8445551:/usr/local/lib/python3.9/dist-packages# nm tableauhyperapi/bin/libtableauhyperapi.so  -gDC | grep hyper_big_numeric_to_double
```

So at runtime the linker must be picking up the tableau distributed shared library when we want the pantab internal one.

This might be because doing `import tableauhyperapi` runs some code that picks up the shared library for FFI calls. I am assuming that gets cached for subsequent library searches but am happy to be corrected on how that works.

To really fix this we should get rid of the tableauhyperapi dependency in the linked message. A workaround as you have already discovered is to ensure that you install a tableauhyperapi python package that contains a shared library with all the symbols pantab was built against, i.e. tableauhyperapi >= 0.0.18618

**Comment by WillAyd** [comment]
Actually I guess if we even remove the hyper dependency it could be possible for users to hit this error with:

```python
import tableauhyperapi # some old version
import pantab
```

So best we can do is upgrade the dependency in `pyproject.toml` to have a minimum of 0.0..18618. If anyone wants to submit that as a PR would gladly review
