### ISSUE TITLE
Make frames_from_hyper not generate hyperd.log

### ISSUE THREAD

**Issue by fxstempfelals** [innobi/pantab#291]
**Is your feature request related to a problem? Please describe.**
`frames_from_hyper` uses a `HyperProcess` that generates a hyperd.log file. I'd like it not to generate the log files by default, or at least have an option to disable logging.

**Describe the solution you'd like**
Adding `{"log_config": ""}` to `HyperProcess` arguments would do it.

```python
def frames_from_hyper(
    source: Union[str, pathlib.Path],
    return_type: Literal["pandas", "polars", "pyarrow"] = "pandas",
):
    """See api.rst for documentation."""
    result = {}

    table_names = []
    with tempfile.TemporaryDirectory() as tmp_dir, tab_api.HyperProcess(
        tab_api.Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU, 
        parameters={"log_config": ""},
    ) as hpe:
        tmp_db = shutil.copy(source, tmp_dir)
        with tab_api.Connection(hpe.endpoint, tmp_db) as connection:
            for schema in connection.catalog.get_schema_names():
                for table in connection.catalog.get_table_names(schema=schema):
                    table_names.append(table)

    for table in table_names:
        result[table] = frame_from_hyper(
            source=source,
            table=table,
            return_type=return_type,
        )

    return result
```

**Describe alternatives you've considered**
`frames_from_hyper` could take a parameter to enable the log file for users that do want it.

**Additional context**
I use pantab 4.1.0.

**Comment by WillAyd** [comment]
Yea that's a definite oversight - we shouldn't be creating the log files at all. Happy to accept a PR to make that change
