### ISSUE TITLE
Old version installed 

### ISSUE THREAD

**Issue by wggwgz** [innobi/pantab#295]
Hi,  

I am trying to install pantab on my Windows machine with ‘pip install pantab’, somehow it automatically installed an old version 2.1.0. When I try to import pantab, it shows an error saying:
“pantab is incompatible with the version of Tableau Hyper API installed on your system….”

I tried to specify the pantab version with pip install, but it says cannot find the version of 4.1.0 or other newer versions.

my python is 3.7.6, my tableauhyperapi is 0.0.18825, the latest (installed with pip). 

So can someone help me how to install latest pantab version, or figure out whatever the cause is?

thank you for your time.

**Comment by WillAyd** [comment]
pantab at the moment only supports pandas 3.9 and above, although that will even get bumped to 3.10 as a minimum soon. We follow the same version support as pandas

3.7 has not been supported in quite some time, so pip is installing whatever the last version was that supported it for you. Will need to upgrade to at least 3.9 (though preferably 3.10+) at this point if you want to use the latest features
