### ISSUE TITLE
Number of columns in new table definition does not match existing

### ISSUE THREAD

**Issue by T-A-GIT** [innobi/pantab#311]
**Describe the bug**
Trying to write bunch of csv files into a hyper extract using pantab version 4.1.0 in append mode. The first create and push happens successfully but when trying to append the next dataframe it gives an error - Number of columns in new table definition does not match existing, even though the second dataframe is one to one lined up with the first set. 

For troubleshooting i have done the following:

set datatypes to string[pyarrow] on all columns to ensure no type mismatch

i also restricted the dataset to just one column and it still gives me the same error.

**Expected behavior**
I reverted to pantab version 3.0.2 and the same code works without issue

Windows 10, python 3.12.3

**Comment by T-A-GIT** [comment]
I had moved to another environment to try workaround it but seems like its happening because of the index column Name="__index_level_0__", Type=BIG_INT, Nullability=Nullability.NULLABLE. Any workaround to mitigate the same.

**Comment by WillAyd** [comment]
Is that column coming from one of your CSV files? I don't believe pantab tries to write the index at all

**Comment by T-A-GIT** [comment]
Hi - Sorry for the delay i tried to go through the entire dataset and i did not find the index column in the raw files. 

Also interesting that the same process on 3.0.2 did not create that column, while version 4.1.0 did have that column.

**Comment by WillAyd** [comment]
Hmm strange. If you can provide a reproducer can take a look

**Comment by WillAyd** [comment]
Closing as I don't have anything to reproduce this with, but happy to reopen if you can provide more details. Thanks!
