### ISSUE TITLE
data with Decimal 0 will fail when frame_to_hyper

### ISSUE THREAD

**Issue by reactyang** [innobi/pantab#339]
**Describe the bug**
data with decimal 0 will fail when frame_to_hyper with error like :
- IndexError: basic_string::insert: __pos (which is 18446744073709551607) > this->size() (which is 1)

**To Reproduce**

```python
change one decimal to 0 or 0E-10, 0.00 in test_decimal.py  will fail the test.
i.e. change line #101 to "0.00" or "0E010"
```

**Expected behavior**
df with 0(decimals) should also be saved to hyper.
**Screenshots**

**Desktop (please complete the following information):**
reproduce in windows/Linux

**Comment by WillAyd** [comment]
Thanks for the bug report - can you provide an MRE to reproduce the issue?

**Comment by WillAyd** [comment]
Also can you confirm which platform you are using? I've seen some strange behavior on Windows with decimals before which may or may not be related

**Comment by WillAyd** [comment]
OK thanks - can you provide a small code sample to reproduce the issue?

**Comment by reactyang** [comment]
https://github.com/innobi/pantab/blob/4edc45ecb489b5ab00732cfacba6e1c27f77e179/tests/test_decimal.py#L101

change to "0.00" or "0E-10" will fail the test. 
looks relate to 
https://github.com/innobi/pantab/blob/4edc45ecb489b5ab00732cfacba6e1c27f77e179/src/pantab/writer.cpp#L365C1-L366C1

**Comment by WillAyd** [comment]
Thanks for bringing this up! This should be fixed in the next release of pantab.

In the meantime, feel free to give it a spin by installing from github:

```
python -m pip install git+https://github.com/innobi/pantab.git
```
