### ISSUE TITLE
Allow sinking and scanning of lazyframes

### ISSUE THREAD

**Issue by skyth540** [innobi/pantab#346]
**Is your feature request related to a problem? Please describe.**
[Lazyframes](https://docs.pola.rs/api/python/stable/reference/lazyframe/index.html) allow for larger-than-memory dataframes to be handled. pantab does not support lazyframes

**Describe the solution you'd like**
a `sink_to_hyper` function similar to [sink_parquet](https://docs.pola.rs/api/python/stable/reference/api/polars.LazyFrame.sink_parquet.html) and a `scan_from_hyper` function similar to [scan_parquet](https://docs.pola.rs/api/python/stable/reference/api/polars.scan_parquet.html) would be very useful for projects involving lazyframes. 

**Describe alternatives you've considered**
I've tried to `sink_parquet` and use [this library](https://github.com/guilhermenoronha/parquet-to-hyper) to convert, however it doesn't work with my file, and that takes extra time and overhead anyhow

**Comment by WillAyd** [comment]
In pantab we don't necessarily want to tie ourselves to any of the libraries this strongly; we just provide one interface and it is up to the library to implement the Arrow C Data specification

I think this is more of a question for polars. You may want to ask about this upstream in an issue like https://github.com/pola-rs/polars/issues/12530 and see what plans they have for implementing that for Lazyframes

**Comment by WillAyd** [comment]
Closing as I don't think there is anything we can do about this in pantab. For libraries to be usable in pandas, they must conform to the Arrow PyCapsule Interface:

https://arrow.apache.org/docs/format/CDataInterface/PyCapsuleInterface.html

So if desired I think should ask for that adherence with LazyFrames upstream

**Comment by skyth540** [comment]
Sounds good. I broke my project into chunks and iterated myself
