### ISSUE TITLE
Allow user to pass connection / hyper instance

### ISSUE THREAD

**Issue by WillAyd** [innobi/pantab#39]
Right now the public facing functions create new Hyper Processes / Connections for the user. This however can be rather expensive (I think 300-400 ms) and limiting for advanced use cases

If someone out there is willing to benchmark and propose an API accordingly would certainly welcome contributions on this

**Comment by mhadi813** [comment]
Hi Will,
I don't have expertise in benchmarking and API but can contribute input and output functions.
For input functions, user can use Google BigQuery/MS Azure SQL, CSV, EXCEL, or arbitrary script.py with requests module to create hyper.
CSV, Excel and script.py could be on local disk, Google Cloud Storage or Azure storage.

For output, hyper could be published to Tableau server in overwrite, createnew, append mode to a tableau server.
Does this align with this enhancement request?
