### ISSUE TITLE
Replace MANIFEST.in

### ISSUE THREAD

**Issue by WillAyd** [innobi/pantab#48]
Would ideally like to move this to the setup.py instead of having the MANIFEST, as the MANIFEST file is pretty poorly documented and I think a packaging relic

@chillerno1

**Comment by chillerno1** [comment]
The MANIFEST.in includes can be added into ``package_data`` of the main setup call and they'll be picked up by sdist. Let me know if you want to do that and I'll create a PR. 

```
package_data={
    ...
    "" : ["README.md"],
    "" : ["LICENSE.txt"],
    },
```

Not sure that solves the documentation issue though.

**Comment by WillAyd** [comment]
Sure that would be great! Not a blocker on the docs for now - most people will just go online for those anyway

**Comment by chillerno1** [comment]
Made an error in my comment earlier, package_data won't pick up files in the base dir but we can use data_files to do this. PR includes this update.
