### ISSUE TITLE
Reorg Project

### ISSUE THREAD

**Issue by WillAyd** [innobi/pantab#65]
I think would be nicer if we followed convention by placing the C files in a `src` folder separate from the Python modules

**Comment by vogelsgesang** [comment]
I agree that moving the C code into a separate `src` would probably be nice.
Which exact layout are you imagining?
```
pantab/_reader.py
pantab/_writer.py
pantab/*.py
pantab/src/cffi.h
pantab/src/pantab.c
pantab/src/...
```

or something different?

**Comment by WillAyd** [comment]
Yea that kind of structure makes sense

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
