### ISSUE TITLE
Working with Schemas example is throwing an error

### ISSUE THREAD

**Issue by chillerno1** [innobi/pantab#73]
**Describe the bug**
Usage Example: Working with Schemas code snippet throws an error due to an unnecessary df arg.

`Traceback (most recent call last):
  File ".\pantabtest.py", line 16, in <module>
    df2 = pantab.frame_from_hyper(df, "example.hyper", table=table)
TypeError: frame_from_hyper() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
`

**To Reproduce**

1. https://pantab.readthedocs.io/en/latest/examples.html#working-with-schemas
2. Copy code snippet.
3. Run the example.

**Expected behavior**
The code snippet should work as expected.

**Desktop (please complete the following information):**
Not applicable

**Additional context**
@WillAyd on the road at the moment but I'll fix this in a PR tonight.

**Comment by WillAyd** [comment]
Nice catch - thanks!
