### ISSUE TITLE
Writing mixed dtypes causes error

### ISSUE THREAD

**Issue by CamDL** [innobi/pantab#81]
One of my data sets has a column that's mixed between integers and strings. The vast majority are integers, but there are a number of string values within the same column. Pandas interprets this column correctly as an object data type, but pantab raises a dtype error when writing to an extract.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\.venv\lib\site-packages\pantab\_writer.py", line 186, in frame_to_hyper
    _insert_frame(df, connection=connection, table=table, table_mode=table_mode)
  File "\.venv\lib\site-packages\pantab\_writer.py", line 162, in _insert_frame
    dtypes,
TypeError: Invalid value "10216040" found (row 0 column 0)

**Comment by WillAyd** [comment]
This is by design. You will want to do `df["column"] = df["column"].astype(str)` or if using pandas 1.0 or greater `df["column"] = df["column"].astype("string")`

**Comment by WillAyd** [comment]
@CamDL the main reason is that the "object" dtype in pandas really allows you to store any arbitrary Python object, which would include strings, numbers, lists, dicts, classes, coroutines, types, etc...

Obviously those aren't translatable to Tableau, so you need to be explicit about the intent and ensure everything is a string (if you do in fact want string). You can't mix types, though there's not a great way to ensure that in pandas before pandas 1.0

With pandas 1.0 if you use the "string" dtype things get a lot less murky

**Comment by CamDL** [comment]
This makes sense. I just naively assumed that an object would automatically be converted to a string when writing in Tableau. While Pandas objects can be anything, it usually does a decent job of sampling the table and assigning the best data type.

Purposefully converting all of the values to strings does in fact solve the dtype error. It’d be nice to sample the table and assign data types within pantab instead of inheriting data types from Pandas directly.


On Jan 16, 2020, at 5:43 PM, William Ayd <notifications@github.com> wrote:

﻿

@CamDL<https://github.com/CamDL> the main reason is that the "object" dtype in pandas really allows you to store any arbitrary Python object, which would include strings, numbers, lists, dicts, classes, coroutines, types, etc...

Obviously those aren't translatable to Tableau, so you need to be explicit about the intent and ensure everything is a string (if you do in fact want string). You can't mix types, though there's not a great way to ensure that in pandas before pandas 1.0

With pandas 1.0 if you use the "string" dtype things get a lot less murky

**Comment by WillAyd** [comment]
Over time the plan would be to disallow object dtypes so I don’t think worth doing any extra inferencing. Just will take some time for the new pandas feature to gain traction

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
