### ISSUE TITLE
Not creating hyper extract in cloud notebook

### ISSUE THREAD

**Issue by dianthaevaristo1211** [innobi/pantab#90]
Tried creating hyper extract in a cloud notebook in gcp. No hyper extract was created. Just a hyperd.log file. Tried the same code in local jupyter notebook, it works. Are there some compatibility issue or problem when creating it in cloud?

![image](https://user-images.githubusercontent.com/61256024/80458194-0234be00-8963-11ea-8df8-5b481fbd6a9a.png)

**Comment by WillAyd** [comment]
Do you get any kind of error message on gcp? If it works locally but not there I *think* probably an issue on the service side

**Comment by WillAyd** [comment]
Closing for lack of info and age - if this is still a problem please let me know
